mysql2: &mysql2
  adapter: mysql2
  database: filterrific_demo_<%= Rails.env %>
  username: root
  encoding: utf8

postgresql: &postgresql
  adapter: postgresql
  database: filterrific_demo_<%= Rails.env %>
  username: postgres
  encoding: utf8

sqlite3: &sqlite3
  adapter: sqlite3
  database: db/filterrific_demo_<%= Rails.env %>.sqlite3

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite3" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
